# SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Editorial

description: File an editorial report.

body:
  - type: markdown
    attributes:
      value: |
        If you find typo, grammar error, or other editorial problems in Macana's
        documentation, source code, or generated website, use this form.

        For grammar errors, links or examples of correct sentense would be appreciated.
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
