# SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Output Bug

description: File a bug report about generated HTML/CSS/JavaScript.

labels:
  - "type: bug (output)"

body:
  - type: markdown
    attributes:
      value: |
        If you think Macana's default theme builder's output violates specs, layout incorrectly,
        or not working as intended, use this form.

        Make sure to test with all browser extension disabled before submitting.
  - type: textarea
    attributes:
      label: Description
      description: If it's related CSS, paste a screenshot. If JavaScript throwing an error, paste a stack trace inside a code fence.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Result / Behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Result / Behavior
    validations:
      required: true
  - type: input
    attributes:
      label: Minimal Reproduction Repository
      description: URL for the minimal reproduction repository, sandbox, or a page of website built using Macana.
      placeholder: "https://example.com/foo/"
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Version tag or SHA commit hash the bug exists.
      placeholder: "v0.1.0"
    validations:
      required: true
  - type: input
    attributes:
      label: System and Browser
      description: If the problem is specific to certain browsers, write OS family, browser name and its version.
      placeholder: "macOS Chrome 124.0"
    validations:
      required: true
